const ROUTE_PATH_MATCH_ALL = '*'
const ROUTE_PATH_ROOT = '/'
const ROUTE_PATH_LOGIN = '/login'
const ROUTE_PATH_DASHBOARD = '/dashboard'
const ROUTE_PATH_ALARM_MANAGEMENT = '/alarm-management'
const ROUTE_PATH_COMPARATIVE_ANALYSIS = '/comparative-analysis'
const ROUTE_PATH_CONSUMPTION_ANALYSIS = '/consumption-analysis'
const ROUTE_PATH_ELECTRICITY_DATA_MANAGEMENT = '/electricity-data-analysis'
const ROUTE_PATH_EQUIPMENT_MANAGEMENT = '/equipment-management'
const ROUTE_PATH_TEMPERATURE_MANAGEMENT = '/temperature-management'
const ROUTE_PATH_WATER_MANAGEMENT = '/water-management'
const ROUTE_PATH_ALARM_LIST = '/alarm-list'
const ROUTE_PATH_EQUIPMENT_LIST = '/equipment-list'
const ROUTE_PATH_GATEWAY_LIST = '/gateway-list'
const ROUTE_PATH_LINE_COMPARISON = '/line-comparison'
const ROUTE_PATH_POWER_LINE_LOSS = '/line-loss'
const ROUTE_PATH_BRANCH_DOCUMENT = '/branch-document'
const ROUTE_PATH_AI_MONITORING = '/ai-monitoring'

export {
  ROUTE_PATH_AI_MONITORING,
  ROUTE_PATH_ALARM_LIST,
  ROUTE_PATH_ALARM_MANAGEMENT,
  ROUTE_PATH_BRANCH_DOCUMENT,
  ROUTE_PATH_COMPARATIVE_ANALYSIS,
  ROUTE_PATH_CONSUMPTION_ANALYSIS,
  ROUTE_PATH_DASHBOARD,
  ROUTE_PATH_ELECTRICITY_DATA_MANAGEMENT,
  ROUTE_PATH_EQUIPMENT_LIST,
  ROUTE_PATH_EQUIPMENT_MANAGEMENT,
  ROUTE_PATH_GATEWAY_LIST,
  ROUTE_PATH_LINE_COMPARISON,
  ROUTE_PATH_LOGIN,
  ROUTE_PATH_MATCH_ALL,
  ROUTE_PATH_POWER_LINE_LOSS,
  ROUTE_PATH_ROOT,
  ROUTE_PATH_TEMPERATURE_MANAGEMENT,
  ROUTE_PATH_WATER_MANAGEMENT
}
